// Update Time 23-11-02 08:45:36
#ifndef __ROBOT_DEFS_H__
#define __ROBOT_DEFS_H__
typedef enum {
ROBOTC_PRINT_INFO=0x00,
ROBOTC_PLUG_IN=0x01,
ROBOTC_PLUG_OUT=0x02,
ROBOTC_CASE_OPEN=0x03,
ROBOTC_CASE_CLOSE=0x04,
ROBOTC_DOCK=0x05,
ROBOTC_UNDOCK=0x06,
ROBOTC_PRESS_BUTTON=0x07,
ROBOTC_REQUEST_BATTERY=0x8,
ROBOTC_CONNECT_HEARING_AIDS=0x9,
ROBOTC_DISCONNECT_HEARING_AIDS=0x10,
ROBOTC_CHARGE_HEARING_AIDS=0x0a,
ROBOTC_CHARGE_HEARING_AIDS_STOP=0x0b,
ROBOTC_GEN_PULSE=0x0c,
ROBOTC_SINGLE_WIRE_SND=0x0d,
ROBOTC_SINGLE_WIRE_REQ=0x0e,
ROBOTC_RESET=0xfe,
ROBOTC_NOT_IMPLEMENTED_YET=0xff,
} ROBOTC_t;
typedef enum {
ROBOTE_PRINT_INFO=0x00,
ROBOTE_PLUG_IN=0x01,
ROBOTE_PLUG_OUT=0x02,
ROBOTE_CASE_OPEN=0x03,
ROBOTE_CASE_CLOSE=0x04,
ROBOTE_DOCK_LEFT=0x05,
ROBOTE_DOCK_RIGHT=0x06,
ROBOTE_DOCK_BOTH=0x07,
ROBOTE_UNDOCK_LEFT=0x08,
ROBOTE_UNDOCK_RIGHT=0x09,
ROBOTE_UNDOCK_BOTH=0x0a,
ROBOTE_PRESS_FN=0x0b,
ROBOTE_PRESS_LEFT=0x0c,
ROBOTE_PRESS_RIGHT=0x0d,
ROBOTE_PRESS_RESET=0x0e,
ROBOTE_PRESS_FN_LONG=0x0f,
ROBOTE_PRESS_RESET_LONG=0x10,
ROBOTE_REQUEST_BATTERY_LEFT=0x11,
ROBOTE_REQUEST_BATTERY_RIGHT=0x12,
ROBOTE_CONNECT_HEARING_AIDS=0x13,
ROBOTE_DISCONNECT_HEARING_AIDS=0x14,
} ROBOTE_t;
typedef enum {
SIDE_LEFT=0x01,
SIDE_RIGHT=0x02,
SIDE_BOTH=0x03,
} SIDE_t;
typedef enum {
BUTTON_FN=0x01,
BUTTON_FN_LONG=0x02,
BUTTON_RST=0x03,
BUTTON_RST_LONG=0x04,
BUTTON_LEFT=0x05,
BUTTON_RIGHT=0x06,
} BUTTON_t;
typedef enum {
CMD_TPYE_STATUS_CHECK=0x01,
CMD_TPYE_APP_CONTROL=0x02,
CMD_TPYE_AUDIO_CHAIN=0x03,
CMD_TPYE_CASE_RELATED_WITH_APP=0x04,
CMD_TPYE_ECHO_CONTROL=0x05,
} CMD_TPYE_t;
typedef enum {
CHECK_CHECK_GENERAL_STATUS=0x01,
CHECK_START_UP_CHECK_STATUS=0x02,
CHECK_APP_BACKGROUND_MODE_CHECK_STATUS=0x03,
CHECK_APP_SEND_LOGS_ACKNOWLEDGE=0x04,
CHECK_APP_USERSTATS_MODE_CHECK_STATUS=0x05,
CHECK_APP_SEND_USERSTATS_ACKNOWLEDGE=0x06,
CHECK_APP_FETCH_BT_DEVICE_INFO=0x07,
CHECK_HA_SEND_DOUBLE_TAP_NOTIFICATION=0x08,
CHECK_CHECK_HARDWARE_VERSION=0x09,
} CHECK_t;
typedef enum {
CONTROL_SWITCH_DEVICE_MODE=0x01,
CONTROL_SET_VOLUME=0x02,
CONTROL_SET_REMOTE_FITTING_MODE=0x03,
CONTROL_SET_TONE=0x04,
CONTROL_GET_LATEST_NOISE=0x05,
CONTROL_LOCK_DEVICE=0x06,
CONTROL_SET_PROMPT_VOLUME=0x07,
CONTROL_SET_BATT_SAVING_AUTOMATIC=0x08,
CONTROL_GET_LTK_DATA=0x09,
CONTROL_SET_UPDATED_PMU_TIME=0x0a,
} CONTROL_t;
typedef enum {
AUDIO_SWITCH_RUNNING_MODE=0x01,
AUDIO_SET_BEAMFORMING_ONOFF=0x02,
AUDIO_UPDATE_HEARING_PROFILE=0x03,
AUDIO_SEND_CONFIG_TO_FW=0x04,
AUDIO_SEND_TEST_CONFIG_IN_REMOTE_FITING=0x05,
AUDIO_SWITCH_ANSI_SETTING=0x06,
AUDIO_FINETUNE_ANSI_RTS_GAIN=0x07,
} AUDIO_t;
typedef enum {
CASE_RELATED_WITH_APP_CASE_STARTUP_INFO_TO_APP=0x01,
CASE_RELATED_WITH_APP_CASE_FUNC_BUTTON_PRESSED_TO_APP=0x02,
CASE_RELATED_WITH_APP_CASE_LONG_BAR_L_PRESSED_TO_APP=0x03,
CASE_RELATED_WITH_APP_CASE_LONG_BAR_R_PRESSED_TO_APP=0x04,
} CASE_RELATED_WITH_APP_t;
typedef enum {
ECHO_CONTROL_CASE_SEND_STARTUP_INFO=0x01,
ECHO_CONTROL_CASE_FUNC_BUTTON_PRESSED=0x02,
ECHO_CONTROL_CASE_LONG_BAR_L_PRESSED=0x03,
ECHO_CONTROL_CASE_LONG_BAR_R_PRESSED=0x04,
ECHO_CONTROL_CASE_PAIRING_COMPLETED=0x05,
} ECHO_CONTROL_t;
#endif // __ROBOT_DEFS_H__
