// Update Time 23-10-25 06:40:20
#ifndef __ROBOT_DEFS_H__
#define __ROBOT_DEFS_H__
typedef enum {
ROBOTC_PRINT_INFO=0x00,
ROBOTC_PLUG_IN=0x01,
ROBOTC_PLUG_OUT=0x02,
ROBOTC_CASE_OPEN=0x03,
ROBOTC_CASE_CLOSE=0x04,
ROBOTC_DOCK=0x05,
ROBOTC_UNDOCK=0x06,
ROBOTC_PRESS_BUTTON=0x07,
ROBOTC_REQUEST_BATTERY=0x8,
ROBOTC_CONNECT_HEARING_AIDS=0x9,
ROBOTC_DISCONNECT_HEARING_AIDS=0x10,
ROBOTC_CHARGE_HEARING_AIDS=0x0a,
ROBOTC_CHARGE_HEARING_AIDS_STOP=0x0b,
ROBOTC_GEN_PULSE=0x0c,
ROBOTC_SINGLE_WIRE_SND=0x0d,
ROBOTC_SINGLE_WIRE_REQ=0x0e,
ROBOTC_RESET=0xfe,
ROBOTC_NOT_IMPLEMENTED_YET=0xff,
} ROBOTC_t;
typedef enum {
ROBOTE_PRINT_INFO=0x00,
ROBOTE_PLUG_IN=0x01,
ROBOTE_PLUG_OUT=0x02,
ROBOTE_CASE_OPEN=0x03,
ROBOTE_CASE_CLOSE=0x04,
ROBOTE_DOCK_LEFT=0x05,
ROBOTE_DOCK_RIGHT=0x06,
ROBOTE_DOCK_BOTH=0x07,
ROBOTE_UNDOCK_LEFT=0x08,
ROBOTE_UNDOCK_RIGHT=0x09,
ROBOTE_UNDOCK_BOTH=0x0a,
ROBOTE_PRESS_FN=0x0b,
ROBOTE_PRESS_LEFT=0x0c,
ROBOTE_PRESS_RIGHT=0x0d,
ROBOTE_PRESS_RESET=0x0e,
ROBOTE_PRESS_FN_LONG=0x0f,
ROBOTE_PRESS_RESET_LONG=0x10,
ROBOTE_REQUEST_BATTERY_LEFT=0x11,
ROBOTE_REQUEST_BATTERY_RIGHT=0x12,
ROBOTE_CONNECT_HEARING_AIDS=0x13,
ROBOTE_DISCONNECT_HEARING_AIDS=0x14,
} ROBOTE_t;
typedef enum {
SIDE_LEFT=0x01,
SIDE_RIGHT=0x02,
SIDE_BOTH=0x03,
} SIDE_t;
typedef enum {
BUTTON_FN=0x01,
BUTTON_FN_LONG=0x02,
BUTTON_RST=0x03,
BUTTON_RST_LONG=0x04,
BUTTON_LEFT=0x05,
BUTTON_RIGHT=0x06,
} BUTTON_t;
#endif // __ROBOT_DEFS_H__
