# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_worker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13remote_worker.proto\x12\rremote_worker\"\xda\x01\n\x12\x43ommandLineRequest\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x12\x0c\n\x04\x61rg0\x18\x02 \x01(\t\x12\x0c\n\x04\x61rg1\x18\x03 \x01(\t\x12\x0c\n\x04\x61rg2\x18\x04 \x01(\t\x12\x0c\n\x04\x61rg3\x18\x05 \x01(\t\x12\x0c\n\x04\x61rg4\x18\x06 \x01(\t\x12\x0c\n\x04\x61rg5\x18\x07 \x01(\t\x12\x0c\n\x04\x61rg6\x18\x08 \x01(\t\x12\x0c\n\x04\x61rg7\x18\t \x01(\t\x12\x0c\n\x04\x61rg8\x18\n \x01(\t\x12\x0c\n\x04\x61rg9\x18\x0b \x01(\t\x12\r\n\x05\x61rg10\x18\x0c \x01(\t\x12\r\n\x05\x61rg11\x18\r \x01(\t\x12\r\n\x05\x61rg12\x18\x0e \x01(\t\"6\n\x10\x43ommandLineReply\x12\x0e\n\x06stream\x18\x01 \x01(\t\x12\x12\n\nreturncode\x18\x02 \x01(\x05\x32\x65\n\x0cRemoteWorker\x12U\n\x0b\x43ommandLine\x12!.remote_worker.CommandLineRequest\x1a\x1f.remote_worker.CommandLineReply\"\x00\x30\x01\x42\x34\n\x16\x66irmware.remote_workerB\x12remote_workerProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remote_worker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026firmware.remote_workerB\022remote_workerProtoP\001\242\002\003HLW'
  _globals['_COMMANDLINEREQUEST']._serialized_start=39
  _globals['_COMMANDLINEREQUEST']._serialized_end=257
  _globals['_COMMANDLINEREPLY']._serialized_start=259
  _globals['_COMMANDLINEREPLY']._serialized_end=313
  _globals['_REMOTEWORKER']._serialized_start=315
  _globals['_REMOTEWORKER']._serialized_end=416
# @@protoc_insertion_point(module_scope)
